# Generated by Django 6.0.1 on 2026-03-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('gym', 'Gym')], default='casual', max_length=20),
        ),
    ]
