# Generated by Django 6.0.1 on 2026-03-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='Black,White,Blue', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='T-shirts', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='Small,Medium,Large,X-Large', max_length=255),
        ),
    ]
